---
title: "revise"
author: "Di Zhang  118020518"
date: "11/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd('/Users/zhangdi/FIN 3380/L4/')
library(dplyr)
library(tidyr)
library(zoo)
load('crsp.beta.RData')
crsp.beta = crsp.beta %>% mutate(date=as.Date(date)) %>% filter((date>='2008-01-01')&(date<'2011-01-01'))
a=crsp.beta
a=a %>% spread(permno,ret)
dt=a$date
library(timeSeries)
ret.mat=as.timeSeries(a)
library(fPortfolio)
eff=portfolioFrontier(data=ret.mat)
eff.min=minvariancePortfolio(data=ret.mat)
wgt=eff.min@portfolio@portfolio$weights
wgt
```

```{r}
port.ret=ret.mat %*% matrix(wgt,length(wgt))
port.ret=as.data.frame(port.ret)
names(port.ret)=c('ret')
port.ret$date=as.yearmon(dt)
head(port.ret)
```

```{r}
load('/Users/zhangdi/FIN 3380/L2/ff.RData')
ff=ff %>% select(date,rf,rmxrf)
ff$date=as.yearmon(ff$date)
port.ret=merge(port.ret,ff,by='date',all.x=F,all.y=F)
port.ret$rf=as.numeric(port.ret$rf)
port.ret$rmxrf=as.numeric(port.ret$rmxrf)
port.ret=port.ret %>% mutate(portxrf=ret-rf)
capm=lm(port.ret$portxrf~port.ret$rmxrf,data=port.ret)
summary(capm)$coefficients
alpha=summary(capm)$coefficients[1]
bata=summary(capm)$coefficients[2]
```

```{r}
load('/Users/zhangdi/FIN 3380/L4/crsp.roll.RData')
library(dplyr)
library(tidyr)
library(zoo)
a=crsp.roll
a=a %>% mutate(date=as.Date(date)) %>% filter(date<='2011-01-01')
ff=read.csv('/Users/zhangdi/FIN 3380/L4/ff_daily.csv',skip=4)
names(ff)=c('date','mkt.rf','smb','hml','rf')
ff=ff %>% filter(!is.na(rf)) %>% mutate(date=as.Date(date,'%Y%m%d')) %>% 
  mutate_at(vars(mkt.rf,smb,hml,rf),~./100)
a=left_join(a,ff,by='date')
a=a %>% mutate(ret.rf=ret-rf)

stock1=a %>% filter(permno==first(permno))
library(tibbletime)
win=252
Roll.Lm=rollify(.f=function(ret.rf,mkt.rf,smb,hml){lm(ret.rf~mkt.rf+smb+hml)},window=win,unlist=FALSE)
stock1=as_tibble(stock1)
tmprst=stock1 %>% mutate(model=Roll.Lm(ret.rf,mkt.rf,smb,hml)) %>% select(date,model) %>% slice(-1:-251)
head(tmprst)

tmprst$model[1:3]
```

```{r}
load('/Users/zhangdi/FIN 3380/L4/nflx.RData')
load('/Users/zhangdi/FIN 3380/L4/sp500.RData')
a=nflx
b=sp500
b=b %>% arrange(date) %>% mutate(sp500=sp500/lag(sp500,1)-1) %>% na.omit()
ff=read.csv('/Users/zhangdi/FIN 3380/L4/ff_daily.csv',skip=4)
colnames(ff) = c("date","mkt.rf","smb","hml","rf")
ff$date = as.Date(ff$date,"%Y%m%d")
ff=ff %>% mutate_at(vars(mkt.rf,smb,hml,rf),~./100) %>% select(date,rf) %>% filter((date>='2012-07-23')&(date<='2013-07-23'))
a.mkt=a %>% left_join(b,by='date') %>% left_join(ff,by='date')
a.mkt=a.mkt %>% mutate_at(vars(nflx,sp500),~.-rf) %>% select(date,nflx,sp500) %>% rename_at(vars(nflx,sp500),~paste0(.,'.rf'))
a.mkt.est=a.mkt %>% filter(date<'2013-07-23')
mkt.model=lm(a.mkt.est$nflx.rf~a.mkt.est$sp500.rf,data=a.mkt.est)
mkt.summary=summary(mkt.model)
mkt.summary
```

```{r}
a.mkt.event = a.mkt %>% filter(date=='2013-07-23')
a.mkt.event$pre=mkt.summary$coefficients[1]+mkt.summary$coefficients[2]*a.mkt.event$sp500.rf
a.mkt.event$abnormal=a.mkt.event$nflx.rf-a.mkt.event$pre
r.sigma=mkt.summary$sigma
a.mkt.event$tstat=a.mkt.event$abnormal/r.sigma
a.mkt.event$pval=2*(1-pt(abs(a.mkt.event$tstat),df=nrow(a.mkt.est)-2))
a.mkt.event
```

```{r}
plot(a$nflx_prc~as.Date(a$date),type='l')
ret.order=a[order(-abs(a$nflx)),]
ret.order
a.mkt.est2=a.mkt %>% mutate(date=as.Date(date)) %>% filter(date<'2013-07-23' & abs(nflx.rf)<quantile(abs(nflx.rf),probs=0.99,type=3))
mkt.model2=lm(a.mkt.est2$nflx.rf~a.mkt.est2$sp500.rf,data=a.mkt.est2)
model2.summary=summary(mkt.model2)
model2.summary
a.mkt.event2=a.mkt %>% filter(date=='2013-07-23') 
a.mkt.event2$pre=model2.summary$coefficients[1]+model2.summary$coefficients[2]*a.mkt.event2$sp500.rf
a.mkt.event2$abnormal=a.mkt.event2$nflx.rf-a.mkt.event2$pre
r.sigma=model2.summary$sigma
a.mkt.event2$tstat=a.mkt.event2$abnormal/r.sigma
a.mkt.event2$pval=2*(1-pt(abs(a.mkt.event2$tstat),df=nrow(a.mkt.est2)))
a.mkt.event2
```

