---
title: "review1"
author: "Di Zhang  118020518"
date: "10/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## long msft and short aapl
```{r}
msft=read.csv('/Users/zhangdi/FIN 3380/L1/msft.csv')
aapl=read.csv('/Users/zhangdi/FIN 3380/L1/aapl.csv')
library(dplyr)
aapl.ret=aapl %>% select(date,prc)
aapl.ret=aapl.ret %>% arrange(date) %>% mutate(aapl.ret=prc/lag(prc,1)-1) %>% select(date,aapl.ret)
msft.ret=msft %>% select(date,prc)
msft.ret=msft.ret %>% arrange(date) %>% mutate(msft.ret=prc/lag(prc,1)-1) %>% select(date,msft.ret)
msft.aapl=aapl.ret %>% inner_join(msft.ret,by='date')
msft.aapl=msft.aapl %>% arrange(date) %>% mutate(ret=msft.ret-aapl.ret) %>% 
  filter(!is.na(aapl.ret))  %>% mutate(cumret=cumprod(ret+1))
plot(msft.aapl$cumret~as.Date(msft.aapl$date),type='l',ylab='return',xlab='date',main='long msft short aapl')
```

## sma
```{r}
aapl=read.csv('/Users/zhangdi/FIN 3380/L1/aapl.csv')
aapl=aapl %>% select(date,prc)
library(zoo)
aapl=aapl %>% mutate(sma50=rollmean(aapl$prc,k=50,fill=NA,align='right'),sma200=rollmean(aapl$prc,k=200,fill=NA,align='right'))
aapl=aapl %>% mutate(date=as.Date(date)) %>% filter(date>='2016-01-01')
plot(aapl$prc~aapl$date,type='l',ylab='prc',xlab='date',main='sma')
lines(aapl$sma50~aapl$date,col='red')
lines(aapl$sma200~aapl$date,col='blue')
legend('topleft',c('prc','sma50','sma200'),lty=c(1,1,1),col=c('black','red','blue'))
#legend & rollmean 
```

## bollinger band
```{r}
aapl=read.csv('/Users/zhangdi/FIN 3380/L1/aapl.csv')
aapl=aapl %>% select(date,prc) %>% mutate(avg=rollmean(prc,k=20,fill=NA,align='right')) %>%
  mutate(sd=rollapply(prc,width=20,FUN=sd,na.rm=T,fill=NA,align='right'))
aapl=aapl %>% arrange(date) %>% filter(substr(date,1,4)=='2016') %>% mutate(up=avg+2*sd,down=avg-2*sd)
yrange=range(aapl[,c('prc','up','down')])
plot(aapl$prc~as.Date(aapl$date),ylim=yrange,type='l',ylab='prc',xlab='date',main='bb')
lines(aapl$up~as.Date(aapl$date),col='red')
lines(aapl$avg~as.Date(aapl$date),col='blue')
lines(aapl$down~as.Date(aapl$date),col='red')
legend('bottomright',c('prc','avg','up','down'),lty=c(1,1,1,1),col=c('black','blue','red','red'))
#filter date by substr: no need to change date to as.Date
#yrang is important
```

## RSI
```{r}
aapl=read.csv('/Users/zhangdi/FIN 3380/L1/aapl.csv')
aapl=aapl %>% select(date,prc) %>% arrange(date) %>% mutate(delta=prc-lag(prc,1)) %>%
  mutate(up=ifelse(delta>0,1,0),down=ifelse(delta<0,1,0)) %>% 
  mutate(up.value=delta*up,down.value=-delta*down) %>%
  mutate(up.avg=rollapply(up.value,width=14,na.rm=T,fill=NA,align='right',FUN=mean),
         down.avg=rollapply(down.value,width=14,na.rm=T,fill=NA,align='right',FUN=mean))
for (i in 15:length(aapl$up.avg)){
  aapl$up.avg[i]=aapl$up.avg[i-1]*13/14+aapl$up.value[i]/14
  aapl$down.avg[i]=aapl$down.avg[i-1]*13/14+aapl$down.value[i]/14
}
aapl=aapl %>% mutate(rs=up.avg/down.avg) %>% mutate(rsi=100-100/(1+rs))
aapl=aapl %>% mutate(date=as.Date(date)) %>% filter(substr(date,1,4)=='2016')
plot(aapl$rsi~as.Date(aapl$date),ylim=c(0,100),type='l',ylab='rsi',xlab='date',main='rsi')
abline(h=c(30,70),col='red')
#ifelse,the second number is the return of the first choice
```

