---
title: "HW6"
author: "Di Zhang  118020518"
date: "12/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd('/Users/zhangdi/FIN 3380/Homework/HW6')
library(dplyr)
```

## Q1
### Q1(a)
```{r}
spread=read.csv('spread.csv')
names(spread)=c('date','rate')
spread=spread %>% mutate(date=as.Date(date),rate=as.numeric(rate))
usedata=spread %>% dplyr::filter(date>='1982-01-01'&date<='2018-12-31')
testdata=spread %>% dplyr::filter(substr(date,1,4)=='2019')
acf(usedata$rate,lag=12)
pacf(usedata$rate,lag=12)
library(fUnitRoots)
adfTest(usedata$rate)
# AR model
ARaic=NULL
ARbic=NULL
for (i in 0:12){
  tmp=arima(usedata$rate,c(i,0,0))
  tmpaic=AIC(tmp)
  tmpbic=BIC(tmp)
  ARaic=append(ARaic,tmpaic)
  ARbic=append(ARbic,tmpbic)
}
cat('under aic, choose lag',which(ARaic==min(ARaic))-1 ,'under bic,choose lag', which(ARbic==min(ARbic))-1,'\n')
# MA model
MAaic=NULL
MAbic=NULL
for (i in 0:12){
  tmp=arima(usedata$rate,c(0,0,i))
  tmpaic=AIC(tmp)
  tmpbic=BIC(tmp)
  MAaic=append(MAaic,tmpaic)
  MAbic=append(MAbic,tmpbic)
}
cat('under aic, choose lag',which(MAaic==min(MAaic))-1 ,'under bic,choose lag', which(MAbic==min(MAbic))-1,'\n')
# Arima model
library(forecast)
AMaic=NULL
AMbic=NULL
for (i in 0:4){
  for (j in 0:12){
    tmp=arima(usedata$rate,c(i,0,j))
    tmpaic=AIC(tmp)
    tmpbic=BIC(tmp)
    aicmodel=c(i,j,tmpaic)
    bicmodel=c(i,j,tmpbic)
    AMaic=rbind(AMaic,aicmodel)
    AMbic=rbind(AMbic,bicmodel)
  }
}
AMaic=as.data.frame(AMaic)
AMbic=as.data.frame(AMbic)
AMaic[which(AMaic$V3==min(AMaic$V3)),]
AMbic[which(AMbic$V3==min(AMbic$V3)),]
cat('under aic, choose use arima(1,0,9),under bic,use arima(1,0,1).','\n')
```

### Q1(b)
```{r}
#for AR model, use lag 3
arima(usedata$rate,c(3,0,0))
cat('the long term mean value is 1.7875','\n')
#for MA model, use lag 10
arima(usedata$rate,c(0,0,10))
cat('the long term mean value is 1.8264','\n')
```

### Q1(c) Make one step prediction recursively for the first half year of 2019
```{r}
ar3one=NULL
ma10one=NULL
amone=NULL
for (k in 1:6){
  ar3=arima(usedata$rate,c(3,0,0))
  ma10=arima(usedata$rate,c(0,0,10))
  am=arima(usedata$rate,c(1,0,1))
  ar3pred=predict(ar3,n.ahead=1)
  ma10pred=predict(ma10,n.ahead=1)
  ampred=predict(am,n.ahead=1)
  ar3one=append(ar3one,ar3pred$pred[1])
  ma10one=append(ma10one,ma10pred$pred[1])
  amone=append(amone,ampred$pred[1])
  usedata=rbind(usedata,testdata[k,])
}
usedata=usedata %>% dplyr::filter(date<='2018-12-01')
# AR(3)
library(lubridate)
tmp=data.frame(date=seq(last(usedata$date)+months(1),by='month',length=6),
               rate=NA,
               pred=ar3one)
tmp=tmp %>% mutate(up=pred+2*sd(pred),down=pred-2*sd(pred))
ar3tmp=tmp %>% select(date,pred)
preddata1=usedata %>% mutate(pred=rate,up=rate,down=rate)
preddata1=rbind(preddata1,tmp)
preddata1=preddata1 %>% dplyr::filter(date>='2017-01-01')
#plot pred 
plot(preddata1$pred~preddata1$date,col='red',
     ylim = range(preddata1[,seq(2,5)],na.rm=T),type='l',
     lwd=2,main='AR3 Forecast',
     xlab = 'Year',
     ylab = 'Rate')
lines(preddata1$up~preddata1$date,lty=3)
lines(preddata1$down~preddata1$date,lty=3)
lines(preddata1$rate~preddata1$date,lwd=2)
# MA(10)
tmp=data.frame(date=seq(last(usedata$date)+months(1),by='month',length=6),
               rate=NA,
               pred=ma10one)
tmp=tmp %>% mutate(up=pred+2*sd(pred),down=pred-2*sd(pred))
ma10tmp=tmp %>% select(date,pred)
preddata2=usedata %>% mutate(pred=rate,up=rate,down=rate)
preddata2=rbind(preddata2,tmp)
preddata2=preddata2 %>% dplyr::filter(date>='2017-01-01')
#plot pred 
plot(preddata2$pred~preddata2$date,col='red',
     ylim = range(preddata2[,seq(2,5)],na.rm=T),type='l',
     lwd=2,main='MA10 Forecast',
     xlab = 'Year',
     ylab = 'Rate')
lines(preddata2$up~preddata2$date,lty=3)
lines(preddata2$down~preddata2$date,lty=3)
lines(preddata2$rate~preddata2$date,lwd=2)
#arima(1,0,1)
tmp=data.frame(date=seq(last(usedata$date)+months(1),by='month',length=6),
               rate=NA,
               pred=amone)
tmp=tmp %>% mutate(up=pred+2*sd(pred),down=pred-2*sd(pred))
amtmp=tmp %>% select(date,pred)
preddata3=usedata %>% mutate(pred=rate,up=rate,down=rate)
preddata3=rbind(preddata3,tmp)
preddata3=preddata3 %>% dplyr::filter(date>='2017-01-01')
#plot pred 
plot(preddata3$pred~preddata3$date,col='red',
     ylim = range(preddata3[,seq(2,5)],na.rm=T),type='l',
     lwd=2,main='ARIMA(1,0,1)',
     xlab = 'Year',
     ylab = 'Rate')
lines(preddata3$up~preddata3$date,lty=3)
lines(preddata3$down~preddata3$date,lty=3)
lines(preddata3$rate~preddata3$date,lwd=2)
```

### Q1(d)
```{r}
testdata=testdata[1:6,]
# AR
mea1=testdata %>% left_join(ar3tmp,by='date')
mea1=mea1 %>% mutate(dif=(rate-pred)^2)
cat('MSE is ',mean(mea1$dif),'\n')
# MA
mea2=testdata %>% left_join(ma10tmp,by='date')
mea2=mea2 %>% mutate(dif=(rate-pred)^2)
cat('MSE is ',mean(mea2$dif),'\n')
# arima
mea3=testdata %>% left_join(amtmp,by='date')
mea3=mea3 %>% mutate(dif=(rate-pred)^2)
cat('MSE is ',mean(mea3$dif),'\n')
cat('So arima(1,0,1) has the best result.')
```

## Q2
### Q2(a)
```{r}
retail=read.csv('retail.csv')
names(retail)=c('date','sale')
retail=retail %>% mutate(date=as.Date(date))
plot(retail$sale~retail$date,type='l',xlab='date',ylab='sales',main='retail sales')
#first difference
retail=retail %>% mutate(dep=sale-dplyr::lag(sale,1)) %>% na.omit()
# seasonal difference
retail=retail %>% mutate(deps=dep-dplyr::lag(dep,12)) %>% na.omit()
```

### Q2(b)
```{r}
#after first difference
plot(retail$dep~retail$date,type='l',main='After first difference')
acf(retail$dep,lag=12)
pacf(retail$deps,lag=12)
#after seasonal difference
plot(retail$deps~retail$date,type='l',main='After seasonal difference')
acf(retail$deps,lag=12)
pacf(retail$deps,lag=12)
```

### Q2(c)
```{r}
retail1=retail %>% dplyr::filter(substr(date,1,4)>='1995'&substr(date,1,4)<='2018')
aic=NULL
bic=NULL
for (i in 0:2){
  for (j in 0:1){
    tmp=arima(retail1$sale,order=c(i,1,j),seasonal=list(order=c(i,1,j),period=12))
    tmpaic=c(i,j,AIC(tmp))
    tmpbic=c(i,j,BIC(tmp))
    aic=rbind(aic,tmpaic)
    bic=rbind(bic,tmpbic)
  }
}
aic=as.data.frame(aic)
bic=as.data.frame(bic)
aic[which(aic$V3==min(aic$V3)),]
bic[which(bic$V3==min(bic$V3)),]
cat('Use arima(retail1$sale,order=c(2,1,1),seasonal=list(order=c(2,1,1),period=12))')
```

### Q2(d)
```{r}
retail1=retail1 %>% select(date,sale)
tmp=arima(retail1$sale,order=c(2,1,1),seasonal=list(order=c(2,1,1),period=12))
tmppred=predict(tmp,n.ahead=9)
tmp=data.frame(date=seq(last(retail1$date)+months(1),by='month',length=9),
               sale=NA,
               pred=tmppred$pred,
               up=tmppred$pred+2*tmppred$se,
               down=tmppred$pred-2*tmppred$se)
preddata=retail1 %>% mutate(pred=sale,up=sale,down=sale)
preddata=rbind(preddata,tmp)
preddata=preddata %>% dplyr::filter(date>='2016-01-01')
#plot pred 
plot(preddata$pred~preddata$date,col='red',
     ylim = range(preddata[,seq(2,5)],na.rm=T),type='l',
     lwd=2,main='ARIMA',
     xlab = 'Year',
     ylab = 'Sale')
lines(preddata$up~preddata$date,lty=3)
lines(preddata$down~preddata$date,lty=3)
lines(preddata$sale~preddata$date,lwd=2)
```

